### ISSUE TITLE
No about.js file.

### ISSUE THREAD

**Issue by arekbartnik** [WebReflection/hn#1]
Build fails (or is incomplete) because there’s no about.js file in client/@/js.

https://github.com/WebReflection/hn/blob/af1c41c69014827a0fb374614dc44593ddfa3896/client/%40/js/view.js#L97

**Comment by WebReflection** [comment]
Ooops, sorry about that, it's in now.

**Comment by WebReflection** [comment]
Actually, everything was missing ... my bad! It should work now.
